from processor.DelayProcessor import DelayProcessor
from processor.RandomProcessor import RandomProcessor
from processor.ZeroProcessor import ZeroProcessor
from processor.DsmrProcessor import DsmrProcessor